### ISSUE TITLE
Mixed Repositories Issue

### ISSUE THREAD

**Issue by 0A7V9A** [mvo5/synaptic#118]
I got mixed versions of packages in linux because I added "debian backports" (as far as i can remember it was "debian backports") repo before but then removed later. Anyhow the packages were already installed by those versions from "debian backports". For example: a random package version like "1:3.0.18-dmo9" stays on top and considered "higher or latest" version than "3.0.19" from "kali-rolling" repo, that's why I want to [force] reinstall ALL (or at least the ones which has issues like that ) packages to "kali-rolling"  versions, and it's creating big issues like removing a lot of softwares and other packages. Are there any easy and safe ways (maybe using apt pinning) to do this in synaptic manager or aptitude or etc?

Here you can see that "1:3.0.18-dmo9" is considered latest and forcing version to "3.0.19" from (kali-rolling repo) is considered as **DOWNGRADING**
![Screenshot_2023-10-22_13-28-29](https://github.com/mvo5/synaptic/assets/41642677/8e7801e4-a860-4456-9e11-973b993eb0d1)

Here i selectively forced verions for vlc packages:
![Screenshot_2023-10-22_13-39-37](https://github.com/mvo5/synaptic/assets/41642677/6dbfc24d-0645-4093-8115-7e69a0c6487c)
![Screenshot_2023-10-22_13-34-30](https://github.com/mvo5/synaptic/assets/41642677/96ceb979-ff36-4420-b6b7-79813b64c6c7)

No broken packages but look at this:
![Screenshot_2023-10-22_17-22-28](https://github.com/mvo5/synaptic/assets/41642677/1e40342d-c1ab-4f31-a77b-9fd666a2c702)

**Comment by trebmuh** [comment]
> "1:3.0.18-dmo9" is considered latest and forcing version to "3.0.19"

This is expected as the epoch number is set to "1" in the dmo9 version. You can see (the debian manual)[https://www.debian.org/doc/debian-policy/ch-controlfields.html] for more information about this (tips: search for "epoch" in the page).
