### ISSUE TITLE
Keep icons in menu item or not?

### ISSUE THREAD

**Issue by xuzhen** [mvo5/synaptic#3]
I was trying to port code using deprecated GtkImageMenuItem, and found these on GTK+ 3 reference manual
> You should consider using icons in menu items only sparingly, and for "objects" (or "nouns") elements only, like bookmarks, files, and links; "actions" (or "verbs") should not have icons.

Should I follow the document and remove most icons in menu item?

**Comment by mvo5** [comment]
Thanks a lot for this question! I think it does make sense to follow the GTK+3 reference manual and remove the icons for most things. Looking forward to it :)
