### ISSUE TITLE
Build fails with apt 6.0 ABI

### ISSUE THREAD

**Issue by rezso** [mvo5/synaptic#50]
Building 0.90 release with apt >= 1.9.11 fails, because apt-pkg/md5.h removed with https://github.com/Debian/apt/commit/e8016805b87bead8eb3dff0d0559c5d9590b721b#diff-f732901b0b601fffd4358fefb725bbb3

**Comment by mvo5** [comment]
Thanks, this particular issue is fixed now, but it looks like there are some more incompatibilities, I pushed what I have but help is welcome, unfortunately I have very little time for synaptic these days :/

**Comment by mvo5** [comment]
I think it works now
