### ISSUE TITLE
Source location?

### ISSUE THREAD

**Issue by Gerardwx** [mvo5/synaptic#51]
README says All development is done at "https://savannah.nongnu.org/projects/synaptic" ... but it appears this repo is the current source?

**Comment by mvo5** [comment]
Thanks, this is indeed a bit dated. I updated the README to point to github.

**Comment by to-ba** [comment]
@mvo5
You should also change the link on https://launchpad.net/synaptic under »Home page«

**Comment by mvo5** [comment]
Thanks, very good point. Updated.
