### ISSUE TITLE
Link to this github as homepage instead of www.nongnu.org/synaptic/

### ISSUE THREAD

**Issue by BryanQuigley** [mvo5/synaptic#61]
I'd also be happy to create a new homepage using github pages if interested.  Either way, it should link to something that is actively maintained.

**Comment by mvo5** [comment]
Hey Bryan - thanks for the offer to help

I would love to link to a new homepage, I'm happy to add you to the project and give you the needed access.

**Comment by BryanQuigley** [comment]
Awesome, just two questions and I'll get started:
1) Should it be in the same main branch as the code?  (Some projects like to have it in a separate branch)
2) Any preference what static generator to use?  If not, I'll likely just go with jeykll or hugo.

**Comment by mvo5** [comment]
Hi,

thanks for your mail!

On Thu, Dec 10, 2020 at 01:56:13PM -0800, BryanQuigley wrote:
> Awesome, just two questions and I'll get started:
> 1) Should it be in the same main branch as the code?  (Some projects
like to have it in a separate branch)

I think I would slightly prefer a different branch but no super strong
opinions. Just feels a bit odd to have the main c++ code mixed with
the website :)

> 2) Any preference what static generator to use?  If not, I'll likely just go with jeykll or hugo.

I'm not much of a web guy, pick whatever you feel most comfortable
with.


Cheers,
 Michael

**Comment by BryanQuigley** [comment]
As their is a user named synaptic I'm not sure how to get a good URL for it in gh pages.  I started a basic section on the built-in wiki - https://github.com/mvo5/synaptic/wiki.  Thoughts on just making that the home page?  As it's just markdown it can be easily converted to a fuller site if wanted in the future

I'll make some tweaks to the readme to make it flow a bit better next.

Cheers!
Bryan

**Comment by mvo5** [comment]
On Mon, Dec 14, 2020 at 10:38:31PM -0800, BryanQuigley wrote:
> As their is a user named synaptic I'm not sure how to get a good URL for it in gh pages.  I started a basic section on the built-in wiki - https://github.com/mvo5/synaptic/wiki.  Thoughts on just making that the home page?  As it's just markdown it can be easily converted to a fuller site if wanted in the future
> 
> I'll make some tweaks to the readme to make it flow a bit better next.

Yeah, that sounds great! Thanks for working on this!

Cheers,
 Michael
