### ISSUE TITLE
Add Termux Compile

### ISSUE THREAD

**Issue by spz2020** [mvo5/synaptic#87]
see https://github.com/termux/x11-packages/issues/290#issuecomment-839906635

**Comment by spz2020** [comment]
@mvo5

**Comment by Yisus7u7** [comment]
![Screenshot_20220403-101909](https://user-images.githubusercontent.com/64093255/161451170-f045a3bb-d8b4-4630-ade2-e97ea457a626.png)
![Screenshot_20220403-170937](https://user-images.githubusercontent.com/64093255/161451171-cfa64bef-ea9a-4ae5-8eea-c15cde42791b.png)


@spz2020

**Comment by spz2020** [comment]
ok
