### ISSUE TITLE
Package list is blown up in version 0.91; please make it dense as it was

### ISSUE THREAD

**Issue by fitojb** [mvo5/synaptic#99]
Just received synaptic 0.91 from the Ubuntu 22.10 archives. The package list now looks like this:

![imatge](https://user-images.githubusercontent.com/554953/176661599-c90f9ffb-685e-44d3-8b17-de4cbd30578b.png)

I am not on a touchscreen or a phone. It’s insulting to only be able to gaze at six list items at any time by default. The icons on the left have been enlarged disproportionately to the rest of the UI, for seemingly no reason.

**Comment by mvo5** [comment]
Thanks, I did a revert in https://github.com/mvo5/synaptic/commit/84f87dc7be096ed7be179faf7d11948d13abf972 and uploaded a new 0.91.1  that might have triggered this. But if that does not help it could be simply something new in gtk that is outside my control (this is mostly just a rebuild) that needs further investigation.

**Comment by mvo5** [comment]
(if that is the case that the revert is not

**Comment by mvo5** [comment]
fwiw, "insulting" is not a nice word in this context, it's certainly not my intention to insult you.

**Comment by fitojb** [comment]
Thank you Michael! And no, the word was not directed at you or anybody – it’s my feeling for the direction GTK has taken… I am tired of debugging its regressions…

**Comment by fitojb** [comment]
New package contains the revert; the list looks sane again. Thanks!
